AGENT="MonologueAgent"
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="KEY_HERE"
LLM_BASE_URL="PROXY_HERE"
LLM_EMBEDDING_MODEL="local"
LLM_TEMPERATURE=0.0
SANDBOX_TYPE="local"
WORKSPACE_BASE="workdir path"
WORKSPACE_MOUNT_PATH="absolute workdir path"
